plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
    repositories {
        maven {
            url = "https://maven2.bai.lol"
            content {
                includeGroup("lol.bai")
                includeGroup("mcp.mobius.waila")
            }
        }
    }

}

loom {
	splitEnvironmentSourceSets()

	mods {
		"apothicspawners" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

    accessWidenerPath = file("src/main/resources/apothicspawners.aw")
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    compileOnly "mcp.mobius.waila:wthit-api:fabric-${wthitVersion}"
    localRuntime "mcp.mobius.waila:wthit:fabric-${wthitVersion}"
//    modRuntimeOnly "lol.bai:badpackets:fabric-${badpacketsVersion}"

}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {
	}
}